# Generated by Django 4.2 on 2024-08-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
